					/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void task1_handler(void){
	while(1){

	}
}
void task2_handler(void){
	while(1){

		}
}
void task3_handler(void){
	while(1){

		}
}
void task4_handler(void){
	while(1){

		}
}

void init_systick_timer(uint32_t TICK_FREQ){

	uint32_t *pSVR = (uint32_t *)0xE000E014;
	uint32_t *pSCSR = (uint32_t*)0xE000E010;
	uint32_t count = (uint32_t) (SYSTICK_TIMER_CLK/TICK_FREQ) -1;

	//clearing the SVR
	*(pSVR) &= ~(0x00FFFFFF);

	//load values into the SVR
	*(pSVR) |=count;

	//Settings for the SysTick Control and Status register

	*(pSCSR) |= (0x00000007); //  _other_bits_|processor clock|counting down to zero asserts the SysTick exception request|counter enabled
}

uint32_t psp_tasks[MAX_TASKS] = {T1_STACK_START,T2_STACK_START,T3_STACK_START,T4_STACK_START};

uint32_t task_handlers[MAX_TASKS];

void init_task_stack(){

	uint32_t * pPSP;

	for(int i=0;i<MAX_TASKS;i++){
		pPSP=(uint32_t*)psp_tasks[i];

		//XPSR
		pPSP--;
		*pPSP=dummy_XPSR;

		//PC
		pPSP--;
		*pPSP=task_handlers[i];

		//LR
		pPSP--;
		*pPSP=0xFFFFFFFD;

		for(int j=0;j<13;j++){
			pPSP--;
			*pPSP=0; //13 times for the 13 GPR
		}

		psp_of_tasks[i]=(uint32_t)pPSP;
	}
}

__attribute__((naked))void init_scheduler_stack(uint32_t scheduler_stack_top){
	//__asm volatile("MSR MSP, R0");
	__asm volatile("MSR MSP,%0": : "r" (scheduler_stack_top) :  );
	__asm volatile("BX LR "); //ASM instruction to return to the main function - "Return from function call"
}

void SysTick_Handler(void){

}
int main(void)
{
    /* Loop forever */

	init_systick_timer(TICK_FREQ);

	task_handlers[0]=(uint32_t *)task1_handler;
	task_handlers[1]=(uint32_t *)task2_handler;
	task_handlers[2]=(uint32_t *)task3_handler;
	task_handlers[3]=(uint32_t *)task4_handler;

	init_task_stack();

	init_scheduler_stack(SCHED_STACK_START);
	for(;;);
}



