/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void task1_handler(void) {
	while (1) {
		printf("Sup, this is task 1\n");
	}
}

void task2_handler(void) {
	while (1) {
		printf("Sup, this is task 2\n");
		;
	}
}

void task3_handler(void) {
	while (1) {
		printf("Sup, this is task 3\n");
		;
	}
}

void task4_handler(void) {
	while (1) {
		printf("Sup, this is task 4\n");
		;
	}
}

extern void initialise_monitor_handles(void);

__attribute__((naked)) void init_scheduler_stack(uint32_t scheduler_start);

void init_systick_timer(uint32_t timer_freq) {
	uint32_t *pSRVR_reg = (uint32_t*) 0xE000E014;
	uint32_t *pSCSR_reg = (uint32_t*) 0xE000E010;
	uint32_t rel_count_val = (SYSTICK_TIMER_CLOCK / timer_freq) - 1;

	//clearing the SVR
	*(pSRVR_reg) &= ~(0x00FFFFFF);

	//Load the value into the SVR
	*(pSRVR_reg) |= rel_count_val;

	*(pSCSR_reg) |= (1 << 1); //enables the systick exception
	*(pSCSR_reg) |= (1 << 2); //indicates processor clock source

	*(pSCSR_reg) |= (1 << 0); //enables the counter

}
__attribute__((naked))void SysTick_Handler(void) {

	/*Saving the context of the curent task*/

	//1.Get the current PSP value
	__asm volatile("MRS R0, PSP");
	//2.Use that to store R4-11's values for that task
	__asm volatile("STMDB R0!,{R4-R11}");
	//the ! is a write-back suffix - updates R0. Also, STMDB is store multiple, decrement before
	__asm volatile("PUSH {LR}");
	//3.Save the context value of the PSP
	__asm volatile("BL save_psp_value");

	/*Retrieve the context of the next*/
	//1.Decide what is the next task to run
	__asm volatile("BL update_next_task");
	//2.Get it's past PSP value
	__asm volatile("BL get_psp_value");
	//3.Load the context of the task onto the scheduler -> retrieve R4-11
	__asm volatile("LDMIA R0!,{R4-R11}");
	//4. Update PSP and exit
	__asm volatile("MSR PSP, R0");

	__asm volatile("POP {LR}");
	__asm volatile("BX LR");

}

void enable_processor_faults(void) {
	uint32_t *pSHCSR = (uint32_t*) 0xE000ED24;

	*pSHCSR |= (1 << 16); //mem manage
	*pSHCSR |= (1 << 17); //bus fault
	*pSHCSR |= (1 << 18); //usage fault
}

uint32_t get_psp_value() {
	return psp_of_tasks[current_task];
}
void save_psp_value(uint32_t current_psp) {
	psp_of_tasks[current_task] = current_psp;
}
void update_next_task() {
	current_task++;
	current_task %= MAX_TASKS; //lol, THIS is what makes it a round robin algo
}
void switch_to_psp() {
	//1. Initialize the PSP with the address of the first task

	//jump to go get the value of the PSP

	__asm volatile("PUSH {LR}");
	//save the connection to the main
	__asm volatile("BL get_psp_value");
	//Init the psp
	__asm volatile("MSR PSP, R0");
	__asm volatile("POP {LR}");

	//2. Change the SP to the PSP via the COntrol register
	__asm volatile("MOV R0,#0x02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile ("BX LR");

}

__attribute__((naked)) void init_scheduler_stack(uint32_t scheduler_start) {
	__asm volatile("MSR MSP,%0": : "r" (scheduler_start) : );
	__asm volatile("BX LR");
	//branch to link reg, this basically gets us back to the main
//	__asm volatile();
}

void init_task_stack(void) {
	uint32_t *pPSP;

	for (int i = 0; i < 4; i++) {
		pPSP = (uint32_t*) psp_of_tasks[i];
		pPSP--;
		*pPSP = 0x01000000; //the XPSR, just to kick things off for the scheduler

		pPSP--; //back to the program counter
		*pPSP = task_handlers[i];

		pPSP--; //LR
		*pPSP = 0xFFFFFFFD; //the return value after the exec

		for (int j = 0; j < 13; j++) {
			pPSP--;
			*pPSP = 0;
		}

		psp_of_tasks[i] = (uint32_t) pPSP; //this saves the value of the PSP for each task into the array
	}
}

int main(void) {
	/* Loop forever */
	initialise_monitor_handles();

	enable_processor_faults();

	init_scheduler_stack(SCHEDULER_STACK_START);

	task_handlers[0] = (uint32_t) task1_handler;
	task_handlers[1] = (uint32_t) task2_handler;
	task_handlers[2] = (uint32_t) task3_handler;
	task_handlers[3] = (uint32_t) task4_handler;

	init_task_stack();

	init_systick_timer(timer_freq);

	switch_to_psp();

	task1_handler();
	for (;;)
		;
}
void HardFault_Handler(void) {
	printf("Exception : Hardfault\n");
	while (1)
		;
}

void MemManage_Handler(void) {
	printf("Exception : MemManage\n");
	while (1)
		;
}

void BusFault_Handler(void) {
	printf("Exception : BusFault\n");
	while (1)
		;
}

